# Generated by Django 6.0.3 on 2026-03-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_blogpost_thumbnail_alter_blogpost_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Main blog cover image', null=True, upload_to='blog/covers/'),
        ),
    ]
