# Generated by Django 6.0.1 on 2026-02-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_blogpost_cover_image_alter_blogpost_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mateusz', max_length=100)),
                ('hero_title', models.CharField(default='Hi, I’m Mateusz', max_length=200)),
                ('hero_description', models.TextField(default='I build web applications, learn Django and create my developer portfolio.')),
                ('hero_image', models.ImageField(blank=True, help_text='Profile photo shown on home page', null=True, upload_to='profile/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
