# Generated by Django 6.0.3 on 2026-03-05 05:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_blogpost_thumbnail_alter_blogpost_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogblock',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Text content for this block (optional)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
