# Generated by Django 5.2.10 on 2026-01-21 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_id_alter_skill_id_skillrequirement'),
        ('portfolio', '0004_me'),
    ]

    operations = [
    ]
