# Generated by Django 6.0.1 on 2026-02-25 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_aboutpage_aboutblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Home', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HomeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('text', models.TextField(blank=True, help_text='Optional text content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/blocks/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='portfolio.homepage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
